# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='upload',
            field=models.FileField(default=2, upload_to=b''),
            preserve_default=False,
        ),
    ]
