# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 20:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fileuploader', '0003_filemodel_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='user',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
