# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='topic_id',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='blah',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crudapp.TopicModel'),
        ),
    ]
