# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_nameform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NameForm',
        ),
    ]
