# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_auto_20160501_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicmodel',
            name='topic_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
