# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0004_auto_20160501_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicmodel',
            name='topic_id',
        ),
    ]
