# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0004_blogmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
