# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 22:35
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0005_remove_topicmodel_topic_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicmodel',
            name='topic',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
