# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 17:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0005_blogmodel_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='submitted_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 29, 17, 22, 46, 423300, tzinfo=utc), verbose_name='date submitted'),
            preserve_default=False,
        ),
    ]
