# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0006_blogmodel_submitted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='title',
            field=models.CharField(default='The Titilating Title', max_length=100),
            preserve_default=False,
        ),
    ]
