# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0006_auto_20160501_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='post',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='topic',
            field=models.CharField(max_length=300),
        ),
    ]
