# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0007_auto_20160501_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmodel',
            name='extra',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
