# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-04 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0007_blogmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='vote',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
