# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0008_postmodel_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
