# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0008_topicmodel_extra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='topic',
            new_name='topicid',
        ),
    ]
