# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0009_auto_20160605_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='report',
            field=models.IntegerField(default=0),
        ),
    ]
