# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0010_blogmodel_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='report',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='report',
            field=models.IntegerField(default=0),
        ),
    ]
