# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0010_auto_20160502_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='topicid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crudapp.TopicModel'),
        ),
    ]
