# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0011_auto_20160502_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='topicid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='topicThing', to='crudapp.TopicModel'),
            preserve_default=False,
        ),
    ]
