# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0011_auto_20160605_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='report',
        ),
    ]
