# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0012_auto_20160502_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='topicid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='crudapp.TopicModel'),
        ),
    ]
