# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0013_auto_20160503_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicmodel',
            old_name='extra',
            new_name='topicAuthor',
        ),
        migrations.AlterField(
            model_name='members',
            name='post',
            field=models.CharField(max_length=100),
        ),
    ]
