# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0013_auto_20160605_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=2),
        ),
    ]
