# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0014_postmodel_year_in_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='forum',
            field=models.CharField(choices=[('L1', 'Level 1'), ('L2', 'Level 2'), ('L3', 'Level 3'), ('L4', 'Level 4')], default='L4', max_length=2),
        ),
    ]
