# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0014_auto_20160505_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmodel',
            name='view',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
