# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0015_topicmodel_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicmodel',
            name='view',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
