# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0016_auto_20160506_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicmodel',
            name='view',
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
