# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0017_auto_20160506_0931'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Members',
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='post',
            field=tinymce.models.HTMLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='topic',
            field=models.CharField(max_length=100),
        ),
    ]
