# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0017_auto_20160607_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
