# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0018_auto_20160607_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicmodel',
            name='forum',
            field=models.CharField(choices=[('Level 1', 'Level 1'), ('level 2', 'Level 2'), ('level 3', 'Level 3'), ('level 4', 'Level 4'), ('level 5', 'Level 5'), ('level 6', 'Level 6')], default='level 4', max_length=2),
        ),
    ]
