# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0019_auto_20160612_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomodel',
            name='category',
            field=models.CharField(choices=[('category 1', 'category 1'), ('category 2', 'category 2')], default='category 2', max_length=10),
        ),
    ]
