# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0020_auto_20160614_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicmodel',
            name='forum',
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='categories',
            field=models.CharField(choices=[('General Help', 'General Help'), ('Submitting Portfolios', 'Submitting Portfolios'), ('General Teaching', 'General Teaching'), ('Level 1 & 2', 'Level 1 & 2'), ('Level 3', 'Level 3'), ('Level 4', 'Level 4'), ('Level 5', 'Level 5'), ('Level 6', 'Level 6')], default='Level 4', max_length=2),
        ),
    ]
