# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0021_auto_20160614_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicmodel',
            name='categories',
            field=models.CharField(choices=[('gh', 'General Help'), ('sp', 'Submitting Portfolios'), ('gt', 'General Teaching'), ('l12', 'Level 1 & 2'), ('l3', 'Level 3'), ('l4', 'Level 4'), ('l5', 'Level 5'), ('l6', 'Level 6')], default='l4', max_length=3),
        ),
    ]
