# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-17 20:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0028_auto_20160614_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infomodel',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='infomodel',
            old_name='vote',
            new_name='postid',
        ),
        migrations.RemoveField(
            model_name='infomodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='infomodel',
            name='name',
        ),
        migrations.AddField(
            model_name='infomodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 17, 20, 55, 37, 19953, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infomodel',
            name='post',
            field=models.CharField(default=datetime.datetime(2016, 6, 17, 20, 56, 6, 129484, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infomodel',
            name='topicid',
            field=models.IntegerField(default=0),
        ),
    ]
