# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-18 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0029_auto_20160617_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infomodel',
            old_name='date',
            new_name='date_pub',
        ),
    ]
