# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-18 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0030_auto_20160618_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomodel',
            name='date_pub',
            field=models.DateTimeField(verbose_name='date_pub'),
        ),
    ]
