# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-18 20:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0032_auto_20160618_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infomodel',
            name='datepub',
        ),
        migrations.AddField(
            model_name='infomodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 18, 20, 0, 0, 124283, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
