# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0039_auto_20160619_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicmodel',
            name='categories',
            field=models.CharField(choices=[('GeneralHelp', 'General Help'), ('SubmittingPortfolios', 'Submitting Portfolios'), ('GeneralTeaching', 'General Teaching'), ('Level12', 'Level 1 & 2'), ('Level 3', 'Level3'), ('Level4', 'Level 4'), ('Level5', 'Level 5'), ('Level6', 'Level 6')], default='Level 4', max_length=30),
        ),
    ]
