# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-14 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0047_auto_20160620_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='posts',
            field=models.IntegerField(default=0),
        ),
    ]
