# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0051_auto_20161014_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='newusermodel',
            name='articles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newusermodel',
            name='files',
            field=models.IntegerField(default=0),
        ),
    ]
